### ISSUE TITLE
directory structure with mixed case

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-webclient#102]
Linux have case-sensitivity file system and have directory structure with mixed case not a good idea for linux.
```
Bundles/       FileIndex/  HashData/  Logs/    ShareCache/
Certificates/  FileLists/  HubLists/  RUNNING  WebServer.xml
```
As suggestion make all dir\files in lower case.

**Comment by maksis** [comment]
Because the file system is case sensitive and some of the config files can be easily shared between multiple platforms (and clients), it makes more sense to always use the same casing. Since all clients based on DC++ are already using config files with mixed-case file names (also on Linux), changing them all to lowercase would bring compatibility issues. 

Generally users shouldn't even be viewing or editing the config files directly (logs excluded).

**Comment by infectormp** [comment]
Sometimes to make something good need broke something.
