### ISSUE TITLE
the webclient is accessible only on ipv6

### ISSUE THREAD

**Issue by biGdada** [airdcpp-web/airdcpp-webclient#122]
the weblient, compiled on FreeBSD, listens on ipv6 only.
root@airdc:/ # sockstat -4 -l
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     airdcppd   87198 21 tcp4   *:21989               *:*
root     airdcppd   87198 24 tcp4   *:26727               *:*
root     airdcppd   87198 26 udp4   *:21989               *:*
root     syslogd    78394 7  udp4   *:514                 *:*
root@airdc:/ # sockstat -6 -l
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     airdcppd   87198 18 tcp6   *:5600                *:*
root     airdcppd   87198 19 tcp6   *:5601                *:*
root     airdcppd   87198 20 tcp6   *:21989               *:*
root     airdcppd   87198 23 tcp6   *:26727               *:*
root     airdcppd   87198 25 udp6   *:21989               *:*
root     syslogd    78394 6  udp6   *:514                 *:*

will provide additional info/logs on demand

**Comment by maksis** [comment]
Yeah, sorry, I should have updated the docs already.

AirDC++ Web Client uses IPv6 natively by default. Since FreeBSD has [IPv4-mapped IPv6 addresses](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses) disabled by default, you can access the client only via an IPv6 address. If you need IPv4 connectivity, you may enable support IPv4-mapped IPv6 addresses from the operating system (future client versions should also add a configurable bind address).

I don't really want to change the current default listening behavior as it provides an easy way to support both protocols simultaneously (unless the person is using FreeBSD with the mapping feature disabled).
