### ISSUE TITLE
Running the webui

### ISSUE THREAD

**Issue by doobnet** [airdcpp-web/airdcpp-webclient#201]
How is the webui intended to be run? Looking at the documentation it says:

```
npm install
npm run build
npm run serve
```

But after this commit [1] the server cannot run in production mode. I have minimal experience with Node. I tried running the webui using Phusion Passenger as well, but that causes other problems.

[1] https://github.com/airdcpp-web/airdcpp-webui/commit/d5f3e9ad7c2808b6b4f7dd2c63b770a4a83122f2

**Comment by maksis** [comment]
Yes, you can't run it in production mode. Production env was originally supported because of http://webdemo.airdcpp.net but it became a bit problematic after the recent bundling changes (and not worth the hassle to maintain) so even the demo UI files are now served by the inbuilt web server. The inbuilt server seems to work well enough for the demo, even though there still seem to be some stability issues left (most likely in websocketpp). 

What is your use case for running a standalone production server?

**Comment by doobnet** [comment]
I just wanted to run it in the most efficient way. After the initial start of the server it takes webpack 40 seconds to build, whatever it builds.

**Comment by maksis** [comment]
I've updated the README to reflect the current state. The development server will always compile the UI in memory so it will take some time to start. The development build is significantly slower than the production build so it's not optimal for regular use.

Is there a reason why you don't use the inbuilt web server in AirDC++? I don't think that it's less efficient than the old production node server.

**Comment by doobnet** [comment]
I plan to run this on my NAS using Docker.

**Comment by maksis** [comment]
I'd go with the integrated web server even on NAS. Are you experiencing problems with it?

**Comment by doobnet** [comment]
No, no problems. I was just asking since the documentation did not seem to be up to date 😃.

**Comment by doobnet** [comment]
I think I'll close this issue now. The documentation has been update and I've got my question answered. Thanks.
