### ISSUE TITLE
Compiling on Debian 9 Stretch

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#247]
I couldn't have compiled on Debian 9 Stretch today because of npm package absence in new repository. Luckily compiled binaries are available now.

**Comment by maksis** [comment]
Thanks for the information, that was a bit surprising. Seems like it was removed due to lack of maintainers. 

There's nothing wrong with using the portable builds as I use them as well and they might even be faster than the regular ones with shared libraries. However, it's still possible to install Node.js from their [own apt repository](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) to get the npm app. I'll add an extra note on the [build dependencies](https://airdcpp-web.github.io/docs/installation/dependencies.html) page.
