### ISSUE TITLE
Web client translations

### ISSUE THREAD

**Issue by egoitzro** [airdcpp-web/airdcpp-webclient#251]
Hello, as with the client version that is installed on an operating system such as windows, I would like the web version to have the option of being able to see in different languages and the user is the one that chooses which one he prefers.

**Comment by evildemons** [comment]
Update?

**Comment by maksis** [comment]
Sorry, no updates

**Comment by egoitzro** [comment]
I have seen that you have put in transifex the texts to translate. https://www.transifex.com/airdcpp/airdcpp/dashboard/

**Comment by maksis** [comment]
Yes, localization support will be added in the next version. I'll post an update when there's a beta UI available with translation support. You can start translating the strings even before that though.

**Comment by maksis** [comment]
I've uploaded new beta builds with translation support: http://web-builds.airdcpp.net/develop/

Instructions for using custom translation files (this may change before the final version is released):

1. Create a new directory `<webui root>/js/locales/<language code>` and put your translation file into that directory (the filename must be `webui.main.json`)
2. If there are existing locale files for the same language in `<webui root>/js/locales`, you must delete/rename those (all files starting with your language code) so that the new files get download

**Comment by maksis** [comment]
Submitting translations is now documented at https://airdcpp-web.github.io/docs/advanced/translations.html
