### ISSUE TITLE
Unable to compile Ubuntu 17.10

### ISSUE THREAD

**Issue by pappabetalar** [airdcpp-web/airdcpp-webclient#258]
### Current UI and client versions:

Trying to compile the latest version of airdcpp

### Operating system:

uname -r
4.13.0-16-generic

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

### Steps to reproduce the issue:

Upgraded to the latest release of Ubuntu and tried to compile airdcpp.
Error:

-- Building with UPNP support (miniupnpc)
CMake Error at /usr/share/cmake-3.9/Modules/FindBoost.cmake:1898 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_regex
          boost_system
          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.

libboost1.61* is not avaible for 17.10 from what i can tell.

**Comment by maksis** [comment]
I've updated the installation instructions: https://airdcpp-web.github.io/docs/installation/dependencies-ubuntu.html

Does it help you to solve the issue? I don't think that maintaining the exact installation command is useful anymore as it breaks with each Ubuntu release due to Boost version updates. Compiling from source is targeted mainly for developers in any case as there are portable binaries available for regular users.
