### ISSUE TITLE
download path variable %[hubNI]

### ISSUE THREAD

**Issue by skimj** [airdcpp-web/airdcpp-webclient#260]
I've tried to use the hub name variable `%[hubNI]` in the download path setting without success. When I set the path to `/somefolder/%[hubNI]/` the download goes into the parent directory `/somefolder/`. I got this variable from the DC++ help page link on the setting parameters here: [https://www.airdcpp.net/component/k2/25-setting-parameters](https://www.airdcpp.net/component/k2/25-setting-parameters) but I now think it only applies to logging. So I'm not sure if this is user error, a bug report, or a feature request.

### Current UI and client versions:
Application version: AirDC++w 2.2.1 x86_64
Web UI version: 2.2.1

### Operating system:
Linux

**Comment by maksis** [comment]
`%[hubNI]` will work in the next version. `%[hub]` should produce the same output in the version that you are using.

**Comment by skimj** [comment]
I'm testing this with `%[hub]` for now but without luck. With this setting `/somefolder/%[hub]/downloading/` the download goes to `/somefolder/downloading/` as though `%[hub]` returned empty?

Just for comparison, I tried %[hubURL] which again was "ignored" or blank (but worked fine in the log path).

I'm a bit lost in the code but is the difference related to
`return ClientManager::getInstance()->getFormatedHubNames(aSource.getHintedUser());` (Transfers.cpp) vs.
`return getClient()->getHubName();` (various)?

**Comment by maksis** [comment]
Oh right, those variables are available only when logging completed transfers, not for download paths. Most of those parameters couldn't even be implemented for download paths (such as `%[speed]` or `%[fileSIsession]`) or are not that practical in such context (files can be downloaded from multiple users via different hubs). `%[username]` and time variables are the only supported parameters for download paths ([source](https://github.com/airdcpp/airgit/blob/94bb0c47d87322a9dedb108f9197c7fc17da1994/airdcpp/airdcpp/QueueManager.cpp#L935)).

Unknown parameters are currently just being erased silently but some kind of notification could possibly be implemented (logging of logging warnings is very much out of question because of possible infinite spamming loops...).
