### ISSUE TITLE
Error running ARM Binaries (v2.3.0)

### ISSUE THREAD

**Issue by schwiltzek** [airdcpp-web/airdcpp-webclient#272]
Hi,

i am trying to run the ARM binaries on my Synology NAS. I'm constantly getting following error. Below the strace you can see my CPUinfo:

![image](https://user-images.githubusercontent.com/36610892/38247833-d870617a-3746-11e8-97ca-66e1f857ddf2.png)

Compiling on my NAS is not an option because it has not enough memory. Is there a way to solve this?

**Comment by maksis** [comment]
It's most likely caused by the fact that the current ARM binaries are targeted for CPUs that support the vfpv4 feature, while some armv7 models only support vfpv3. Another user also run into the same issue so I will recompile the arm binaries to use vfpv3 instead. I will post an update when the updated binaries are available.

**Comment by maksis** [comment]
The new build is now available: http://web-builds.airdcpp.net/stable/airdcpp_2.3.0_webui-2.3.0_armhf_portable.tar.gz

Hopefully it solves the issue.

**Comment by schwiltzek** [comment]
First of all i would like to thank you :)

Unfortunately i did not solve the problem. Still the same error on startup :(

**Comment by maksis** [comment]
Ok, I probably need to target Cortex-A8 instead of A7. Seems like the versioning of ARM processors is kind of... confusing: https://community.arm.com/processors/f/discussions/5967/what-are-the-main-differences-between-cortex-a7-a9-a53/25406#25406

**Comment by maksis** [comment]
Please try the latest build: http://web-builds.airdcpp.net/stable/airdcpp_2.3.0_webui-2.3.0_armhf_portable.tar.gz
