### ISSUE TITLE
Feature Request: TTH search enhancement

### ISSUE THREAD

**Issue by DaSilva1** [airdcpp-web/airdcpp-webclient#303]
This is a feature request for the Windows client (3.53 x64 on Win10) but unfortunately despite trying to edit my post for the last 10 damn minutes (and even trying to post as an image), your effing forum keeps complaining that "Akismet says your post is spam". (Sorry, quite angry by now and had to again create an account here just to try and post this. Please fix your completely user-unfriendly forum ASAP.)

Feature Request:

Another popular client I switched from just now (ok, it was Apex 😃) has a nice feature I'm missing sorely in Air. If I paste a TTH hash value in the search field and press Enter or the Search button, Apex automatically detects this and changes the File Type to TTH. So simple but saves a couple of unnecessary clicks that Air requires.

Please add this to Air too. Additionally, if anything _other_ than a TTH value is pasted, Air can automatically switch back to the default "Any" File Type.

**Comment by Kcchouette** [comment]
@DaSilva1 maybe you should open an issue on the windows project, which is located [here](https://github.com/airdcpp/airgit)

**Comment by maksis** [comment]
Unfortunately the web site is quite outdated and some checks were added because of a spam problem but the solution definitely isn't perfect. You can also try posting the feature requests to https://github.com/airdcpp/airgit or https://bugs.launchpad.net/airdcpp/+bugs?orderby=-date_last_updated&start=0 

The Windows GUI isn't currently being actively developed what comes to adding of new features but you'll never know about the future. I'll close this issue to keep the issue tracker focused on the right project (and because this feature also exists in the Web UI).
