### ISSUE TITLE
Can I change the share profile even though there is not the adc/adcs:// prefix in the hub address?

### ISSUE THREAD

**Issue by Horuyuki** [airdcpp-web/airdcpp-webclient#392]
**Is your feature request related to a problem? Please describe.**
Currently cannot share a specific profile unless there is an adc/adcs:// prefix in the hub address. I am in a sharing hub in which there is no such prefix, and adding the prefix resulting in me unable to connect.

**Describe the solution you'd like**
Even if I enter a hub address not beginning with adc/adcs://, I would still be able to share a profile that I desire, instead of the global default option only.

https://i.imgur.com/AxaixZN.png

**Describe alternatives you've considered**

Have no idea what else I can do to share a different profile other than the global default.

**Additional context**
If it can be added by next version, would you also update the AUR repo package soon after too?
Or could this be a bug / config in settings I need to change?

**Comment by maksis** [comment]
That restriction is fully intentional. Custom share profiles can't be used in non-ADC hubs because of the unreliable way of identifying users in them. If you want to use custom share profiles, you can try to convince the owners of such hubs to switch to an ADC hubsoft (that would also provide various other benefits for AirDC++ users).

**Comment by Horuyuki** [comment]
Understand, thank you for clearing that up!

**Comment by Horuyuki** [comment]
Thank you for the clear up!
