### ISSUE TITLE
Find NFO from Search result with directories fail

### ISSUE THREAD

**Issue by dk-opt1** [airdcpp-web/airdcpp-webclient#427]
**Application version**
AirDC++w 2.11.2 armv7l

**Web UI version**
2.11.2

Using Find NFO on a folder containing .nfo file from Search. 

Error msg:
Download failed
File not available

It also displays filename of some other random .nfo file in the file viewer, which seem to be the same file every time for that particular directory in the Search result list. 

Viewing Result details, then browsing share and viewing the NFO file in question works.

**Comment by maksis** [comment]
This is an issue with incorrectly working hubsofts that forward the NFO search command that is targeted to a single user to all users in the hub. You should be able to spot the failing hub by looking for a spam of "File not available" messages from the main chat. This needs to be fixed by the owners of such hubs.

See https://github.com/luadch/luadch/issues/197
